language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
script: phpunit Test.php